# Generated by Django 5.2.13 on 2026-04-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=140)),
                ("badge", models.CharField(blank=True, default="", max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "conditions_titre",
                    models.CharField(blank=True, default="Conditions", max_length=80),
                ),
                (
                    "conditions",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "remise_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("actif", models.BooleanField(default=True)),
                ("media", models.FileField(blank=True, null=True, upload_to="offers/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-actif", "-updated_at", "-created_at"],
            },
        ),
    ]
