# Generated by Django 5.2.13 on 2026-04-28 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "terrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="portal.terrain",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "heure_debut"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("heure_fin__gt", models.F("heure_debut"))),
                        name="availability_end_after_start",
                    )
                ],
            },
        ),
    ]
