# Generated by Django 5.2.13 on 2026-04-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="reservation",
            name="contact_nom",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="reservation",
            name="contact_tel",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
